In [3]:
import numpy as np
import pandas as pd

In [32]:
import numpy as np

class DistanceBasedClassifier:
    def __init__(self, labels=2):
        self.num_labels = labels
        self.centers = {}

    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)

        unique_labels = np.unique(y)
        print("Classes:", unique_labels)

        # Compute centroid for each class
        for label in unique_labels:
            self.centers[label] = np.mean(X[y == label], axis=0)

    def predict(self, X):
        X = np.array(X)
        predictions = []

        for x in X:
            predictions.append(self.calculate_distance(x))

        return np.array(predictions)

    def calculate_distance(self, x):
        distances = {}

        # Compute distance from each class center
        for label, center in self.centers.items():
            distances[label] = np.linalg.norm(x - center)

        # Return label with minimum distance
        return min(distances, key=distances.get)


In [33]:
x=np.array([[1,2],[3,4]])
y=[0,1]

In [34]:
x

array([[1, 2],
       [3, 4]])

In [35]:
y

[0, 1]

In [36]:
model=DistanceBasedClassifier(2)

In [37]:
model.fit(x,y)

Classes: [0 1]


In [38]:
model.centers

{0: array([1., 2.]), 1: array([3., 4.])}

In [39]:
model.predict([[1.5,1]])

array([0])

In [40]:
model.predict([[3,4]])

array([1])